namespace ComposeWellness.Services;

/// <summary>Sink for update output. Implemented by the coordinator, consumed by the stack update service.</summary>
public interface IUpdateLog
{
    /// <summary>Message generated by Compose Wellness itself.</summary>
    void App(string text);

    /// <summary>Raw line from a child process.</summary>
    void Process(string text);
}
