namespace ComposeWellness.Models;

public enum LogSource
{
    /// <summary>Message generated by Compose Wellness itself.</summary>
    App,

    /// <summary>Raw stdout or stderr line from Docker or a custom script.</summary>
    Process,
}

/// <summary>
/// One line of update output. <paramref name="Sequence"/> increases monotonically for the
/// lifetime of the service so browsers can resume from the last line they received.
/// </summary>
public sealed record LogEntry(long Sequence, DateTimeOffset Timestamp, LogSource Source, string Text);
